# Generated by Django 4.2.5 on 2023-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('emailAddress', models.CharField(default='johndoe@gmail.com', max_length=100)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('type', models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient')], default='S', max_length=1)),
            ],
        ),
    ]
