# Generated by Django 4.2.5 on 2023-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
